version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000" 
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=superstrongpass
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superstrongpass
  
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379    
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A app beat
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=superstrongpass
    depends_on:
      - db
      - redis
      - app
  celery-feed-worker:
    restart: always
    build:
      context: .
    command: celery -A app worker -Q ${FEED_CELERY_QUEUE}
    